pub enum Feature {
    // lexicon lookups
    SWEAR_WORDS,
    FIRST_PERSON_PRONOUNS,
    SECOND_PERSON_PRONOUNS,
    MODAL_ADVERBS,
    ACTION_ADVERBS,
    MANNER_ADVERBS,
    SUPERLATIVE_FORMS,
    COMPARATIVE_FORMS,
    STRONGLY_SUBJECTIVE_WORDS,
    NEGATIONS,
    NEGATIVE_OPINION_WORDS,
    POSITIVE_OPINION_WORDS,

    // symbol lookups
    NUMBERS,
    EXCLAMATION_AND_QUESTION_MARKS,
    QUOTATION_MARKS,
    WORD_COUNT,

    // other
    DIVISIVE_TOPICS,

    // new ones
    EFFECT_WORD_SUM,
    CAPITALIZED_WORDS,
    INTENSIFIER_ADVERBS,
    EMPHASIS,
    RHETORICAL_QUESTIONS,
    INCONSISTENCY,
    CONDITIONALS,
    GENERALISATION,
    NECESSITY,
}

//
//      LABELS
//

pub enum TrueFalseLabel {
    True,
    False,
}