// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/news_dataset_sentences.proto

package no.tryxelindustries.java_feature_gen.entitys.protos;

public final class DatasetSentenceProtos {
  private DatasetSentenceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_java_feature_gen_NewsEntrySentences_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_java_feature_gen_NewsEntrySentences_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_java_feature_gen_DatasetSentences_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_java_feature_gen_DatasetSentences_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"proto/news_dataset_sentences.proto\022\020ja" +
      "va_feature_gen\"X\n\022NewsEntrySentences\022\n\n\002" +
      "id\030\001 \001(\005\022\024\n\014publish_date\030\002 \001(\003\022\r\n\005label\030" +
      "\004 \001(\t\022\021\n\tsentences\030\005 \003(\t\"d\n\020DatasetSente" +
      "nces\022\024\n\014dataset_name\030\001 \001(\t\022:\n\014news_entri" +
      "es\030\002 \003(\0132$.java_feature_gen.NewsEntrySen" +
      "tencesBN\n3no.tryxelindustries.java_featu" +
      "re_gen.entitys.protosB\025DatasetSentencePr" +
      "otosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_java_feature_gen_NewsEntrySentences_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_java_feature_gen_NewsEntrySentences_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_java_feature_gen_NewsEntrySentences_descriptor,
        new java.lang.String[] { "Id", "PublishDate", "Label", "Sentences", });
    internal_static_java_feature_gen_DatasetSentences_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_java_feature_gen_DatasetSentences_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_java_feature_gen_DatasetSentences_descriptor,
        new java.lang.String[] { "DatasetName", "NewsEntries", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
