// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/news_dataset_sentences.proto

package no.tryxelindustries.java_feature_gen.entitys.protos;

/**
 * Protobuf type {@code java_feature_gen.NewsEntrySentences}
 */
public final class NewsEntrySentences extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:java_feature_gen.NewsEntrySentences)
    NewsEntrySentencesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NewsEntrySentences.newBuilder() to construct.
  private NewsEntrySentences(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NewsEntrySentences() {
    label_ = "";
    sentences_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NewsEntrySentences();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NewsEntrySentences(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 16: {

            publishDate_ = input.readInt64();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            label_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              sentences_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            sentences_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        sentences_ = sentences_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return no.tryxelindustries.java_feature_gen.entitys.protos.DatasetSentenceProtos.internal_static_java_feature_gen_NewsEntrySentences_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return no.tryxelindustries.java_feature_gen.entitys.protos.DatasetSentenceProtos.internal_static_java_feature_gen_NewsEntrySentences_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences.class, no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int PUBLISH_DATE_FIELD_NUMBER = 2;
  private long publishDate_;
  /**
   * <code>int64 publish_date = 2;</code>
   * @return The publishDate.
   */
  @java.lang.Override
  public long getPublishDate() {
    return publishDate_;
  }

  public static final int LABEL_FIELD_NUMBER = 4;
  private volatile java.lang.Object label_;
  /**
   * <code>string label = 4;</code>
   * @return The label.
   */
  @java.lang.Override
  public java.lang.String getLabel() {
    java.lang.Object ref = label_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      label_ = s;
      return s;
    }
  }
  /**
   * <code>string label = 4;</code>
   * @return The bytes for label.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLabelBytes() {
    java.lang.Object ref = label_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      label_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SENTENCES_FIELD_NUMBER = 5;
  private com.google.protobuf.LazyStringList sentences_;
  /**
   * <code>repeated string sentences = 5;</code>
   * @return A list containing the sentences.
   */
  public com.google.protobuf.ProtocolStringList
      getSentencesList() {
    return sentences_;
  }
  /**
   * <code>repeated string sentences = 5;</code>
   * @return The count of sentences.
   */
  public int getSentencesCount() {
    return sentences_.size();
  }
  /**
   * <code>repeated string sentences = 5;</code>
   * @param index The index of the element to return.
   * @return The sentences at the given index.
   */
  public java.lang.String getSentences(int index) {
    return sentences_.get(index);
  }
  /**
   * <code>repeated string sentences = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the sentences at the given index.
   */
  public com.google.protobuf.ByteString
      getSentencesBytes(int index) {
    return sentences_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (publishDate_ != 0L) {
      output.writeInt64(2, publishDate_);
    }
    if (!getLabelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, label_);
    }
    for (int i = 0; i < sentences_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, sentences_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (publishDate_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, publishDate_);
    }
    if (!getLabelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, label_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < sentences_.size(); i++) {
        dataSize += computeStringSizeNoTag(sentences_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getSentencesList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences)) {
      return super.equals(obj);
    }
    no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences other = (no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences) obj;

    if (getId()
        != other.getId()) return false;
    if (getPublishDate()
        != other.getPublishDate()) return false;
    if (!getLabel()
        .equals(other.getLabel())) return false;
    if (!getSentencesList()
        .equals(other.getSentencesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + PUBLISH_DATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPublishDate());
    hash = (37 * hash) + LABEL_FIELD_NUMBER;
    hash = (53 * hash) + getLabel().hashCode();
    if (getSentencesCount() > 0) {
      hash = (37 * hash) + SENTENCES_FIELD_NUMBER;
      hash = (53 * hash) + getSentencesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code java_feature_gen.NewsEntrySentences}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:java_feature_gen.NewsEntrySentences)
      no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentencesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return no.tryxelindustries.java_feature_gen.entitys.protos.DatasetSentenceProtos.internal_static_java_feature_gen_NewsEntrySentences_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return no.tryxelindustries.java_feature_gen.entitys.protos.DatasetSentenceProtos.internal_static_java_feature_gen_NewsEntrySentences_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences.class, no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences.Builder.class);
    }

    // Construct using no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      publishDate_ = 0L;

      label_ = "";

      sentences_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return no.tryxelindustries.java_feature_gen.entitys.protos.DatasetSentenceProtos.internal_static_java_feature_gen_NewsEntrySentences_descriptor;
    }

    @java.lang.Override
    public no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences getDefaultInstanceForType() {
      return no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences.getDefaultInstance();
    }

    @java.lang.Override
    public no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences build() {
      no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences buildPartial() {
      no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences result = new no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.publishDate_ = publishDate_;
      result.label_ = label_;
      if (((bitField0_ & 0x00000001) != 0)) {
        sentences_ = sentences_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.sentences_ = sentences_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences) {
        return mergeFrom((no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences other) {
      if (other == no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getPublishDate() != 0L) {
        setPublishDate(other.getPublishDate());
      }
      if (!other.getLabel().isEmpty()) {
        label_ = other.label_;
        onChanged();
      }
      if (!other.sentences_.isEmpty()) {
        if (sentences_.isEmpty()) {
          sentences_ = other.sentences_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureSentencesIsMutable();
          sentences_.addAll(other.sentences_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private long publishDate_ ;
    /**
     * <code>int64 publish_date = 2;</code>
     * @return The publishDate.
     */
    @java.lang.Override
    public long getPublishDate() {
      return publishDate_;
    }
    /**
     * <code>int64 publish_date = 2;</code>
     * @param value The publishDate to set.
     * @return This builder for chaining.
     */
    public Builder setPublishDate(long value) {
      
      publishDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 publish_date = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPublishDate() {
      
      publishDate_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object label_ = "";
    /**
     * <code>string label = 4;</code>
     * @return The label.
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string label = 4;</code>
     * @return The bytes for label.
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string label = 4;</code>
     * @param value The label to set.
     * @return This builder for chaining.
     */
    public Builder setLabel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      label_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string label = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLabel() {
      
      label_ = getDefaultInstance().getLabel();
      onChanged();
      return this;
    }
    /**
     * <code>string label = 4;</code>
     * @param value The bytes for label to set.
     * @return This builder for chaining.
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      label_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList sentences_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureSentencesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        sentences_ = new com.google.protobuf.LazyStringArrayList(sentences_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string sentences = 5;</code>
     * @return A list containing the sentences.
     */
    public com.google.protobuf.ProtocolStringList
        getSentencesList() {
      return sentences_.getUnmodifiableView();
    }
    /**
     * <code>repeated string sentences = 5;</code>
     * @return The count of sentences.
     */
    public int getSentencesCount() {
      return sentences_.size();
    }
    /**
     * <code>repeated string sentences = 5;</code>
     * @param index The index of the element to return.
     * @return The sentences at the given index.
     */
    public java.lang.String getSentences(int index) {
      return sentences_.get(index);
    }
    /**
     * <code>repeated string sentences = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the sentences at the given index.
     */
    public com.google.protobuf.ByteString
        getSentencesBytes(int index) {
      return sentences_.getByteString(index);
    }
    /**
     * <code>repeated string sentences = 5;</code>
     * @param index The index to set the value at.
     * @param value The sentences to set.
     * @return This builder for chaining.
     */
    public Builder setSentences(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSentencesIsMutable();
      sentences_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string sentences = 5;</code>
     * @param value The sentences to add.
     * @return This builder for chaining.
     */
    public Builder addSentences(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSentencesIsMutable();
      sentences_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string sentences = 5;</code>
     * @param values The sentences to add.
     * @return This builder for chaining.
     */
    public Builder addAllSentences(
        java.lang.Iterable<java.lang.String> values) {
      ensureSentencesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, sentences_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string sentences = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSentences() {
      sentences_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string sentences = 5;</code>
     * @param value The bytes of the sentences to add.
     * @return This builder for chaining.
     */
    public Builder addSentencesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureSentencesIsMutable();
      sentences_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:java_feature_gen.NewsEntrySentences)
  }

  // @@protoc_insertion_point(class_scope:java_feature_gen.NewsEntrySentences)
  private static final no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences();
  }

  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NewsEntrySentences>
      PARSER = new com.google.protobuf.AbstractParser<NewsEntrySentences>() {
    @java.lang.Override
    public NewsEntrySentences parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NewsEntrySentences(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NewsEntrySentences> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NewsEntrySentences> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySentences getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

