// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/news_dataset_semantic_features.proto

package no.tryxelindustries.java_feature_gen.entitys.protos;

/**
 * Protobuf type {@code java_feature_gen.NewsEntrySemanticFeatures}
 */
public final class NewsEntrySemanticFeatures extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:java_feature_gen.NewsEntrySemanticFeatures)
    NewsEntrySemanticFeaturesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NewsEntrySemanticFeatures.newBuilder() to construct.
  private NewsEntrySemanticFeatures(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NewsEntrySemanticFeatures() {
    result_ = java.util.Collections.emptyList();
    label_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NewsEntrySemanticFeatures();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NewsEntrySemanticFeatures(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 16: {

            publishDate_ = input.readInt64();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              result_ = new java.util.ArrayList<no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult>();
              mutable_bitField0_ |= 0x00000001;
            }
            result_.add(
                input.readMessage(no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult.parser(), extensionRegistry));
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            label_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        result_ = java.util.Collections.unmodifiableList(result_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return no.tryxelindustries.java_feature_gen.entitys.protos.DatasetSemanticFeaturesProtos.internal_static_java_feature_gen_NewsEntrySemanticFeatures_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return no.tryxelindustries.java_feature_gen.entitys.protos.DatasetSemanticFeaturesProtos.internal_static_java_feature_gen_NewsEntrySemanticFeatures_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.class, no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.Builder.class);
  }

  /**
   * Protobuf enum {@code java_feature_gen.NewsEntrySemanticFeatures.FeatureType}
   */
  public enum FeatureType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>WORD_COUNT = 0;</code>
     */
    WORD_COUNT(0),
    /**
     * <code>SWEAR_WORDS = 1;</code>
     */
    SWEAR_WORDS(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>WORD_COUNT = 0;</code>
     */
    public static final int WORD_COUNT_VALUE = 0;
    /**
     * <code>SWEAR_WORDS = 1;</code>
     */
    public static final int SWEAR_WORDS_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FeatureType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static FeatureType forNumber(int value) {
      switch (value) {
        case 0: return WORD_COUNT;
        case 1: return SWEAR_WORDS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FeatureType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FeatureType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FeatureType>() {
            public FeatureType findValueByNumber(int number) {
              return FeatureType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.getDescriptor().getEnumTypes().get(0);
    }

    private static final FeatureType[] VALUES = values();

    public static FeatureType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private FeatureType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:java_feature_gen.NewsEntrySemanticFeatures.FeatureType)
  }

  public interface FeatureResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:java_feature_gen.NewsEntrySemanticFeatures.FeatureResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.java_feature_gen.NewsEntrySemanticFeatures.FeatureType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.java_feature_gen.NewsEntrySemanticFeatures.FeatureType type = 1;</code>
     * @return The type.
     */
    no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureType getType();

    /**
     * <code>double value = 2;</code>
     * @return The value.
     */
    double getValue();
  }
  /**
   * Protobuf type {@code java_feature_gen.NewsEntrySemanticFeatures.FeatureResult}
   */
  public static final class FeatureResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:java_feature_gen.NewsEntrySemanticFeatures.FeatureResult)
      FeatureResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FeatureResult.newBuilder() to construct.
    private FeatureResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FeatureResult() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FeatureResult();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FeatureResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 17: {

              value_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return no.tryxelindustries.java_feature_gen.entitys.protos.DatasetSemanticFeaturesProtos.internal_static_java_feature_gen_NewsEntrySemanticFeatures_FeatureResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return no.tryxelindustries.java_feature_gen.entitys.protos.DatasetSemanticFeaturesProtos.internal_static_java_feature_gen_NewsEntrySemanticFeatures_FeatureResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult.class, no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.java_feature_gen.NewsEntrySemanticFeatures.FeatureType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.java_feature_gen.NewsEntrySemanticFeatures.FeatureType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureType getType() {
      @SuppressWarnings("deprecation")
      no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureType result = no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureType.valueOf(type_);
      return result == null ? no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureType.UNRECOGNIZED : result;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private double value_;
    /**
     * <code>double value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public double getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureType.WORD_COUNT.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (value_ != 0D) {
        output.writeDouble(2, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureType.WORD_COUNT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (value_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult)) {
        return super.equals(obj);
      }
      no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult other = (no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult) obj;

      if (type_ != other.type_) return false;
      if (java.lang.Double.doubleToLongBits(getValue())
          != java.lang.Double.doubleToLongBits(
              other.getValue())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getValue()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code java_feature_gen.NewsEntrySemanticFeatures.FeatureResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:java_feature_gen.NewsEntrySemanticFeatures.FeatureResult)
        no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return no.tryxelindustries.java_feature_gen.entitys.protos.DatasetSemanticFeaturesProtos.internal_static_java_feature_gen_NewsEntrySemanticFeatures_FeatureResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return no.tryxelindustries.java_feature_gen.entitys.protos.DatasetSemanticFeaturesProtos.internal_static_java_feature_gen_NewsEntrySemanticFeatures_FeatureResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult.class, no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult.Builder.class);
      }

      // Construct using no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        value_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return no.tryxelindustries.java_feature_gen.entitys.protos.DatasetSemanticFeaturesProtos.internal_static_java_feature_gen_NewsEntrySemanticFeatures_FeatureResult_descriptor;
      }

      @java.lang.Override
      public no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult getDefaultInstanceForType() {
        return no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult.getDefaultInstance();
      }

      @java.lang.Override
      public no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult build() {
        no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult buildPartial() {
        no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult result = new no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult(this);
        result.type_ = type_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult) {
          return mergeFrom((no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult other) {
        if (other == no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getValue() != 0D) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.java_feature_gen.NewsEntrySemanticFeatures.FeatureType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.java_feature_gen.NewsEntrySemanticFeatures.FeatureType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.java_feature_gen.NewsEntrySemanticFeatures.FeatureType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureType getType() {
        @SuppressWarnings("deprecation")
        no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureType result = no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureType.valueOf(type_);
        return result == null ? no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureType.UNRECOGNIZED : result;
      }
      /**
       * <code>.java_feature_gen.NewsEntrySemanticFeatures.FeatureType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.java_feature_gen.NewsEntrySemanticFeatures.FeatureType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private double value_ ;
      /**
       * <code>double value = 2;</code>
       * @return The value.
       */
      @java.lang.Override
      public double getValue() {
        return value_;
      }
      /**
       * <code>double value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(double value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        
        value_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:java_feature_gen.NewsEntrySemanticFeatures.FeatureResult)
    }

    // @@protoc_insertion_point(class_scope:java_feature_gen.NewsEntrySemanticFeatures.FeatureResult)
    private static final no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult();
    }

    public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FeatureResult>
        PARSER = new com.google.protobuf.AbstractParser<FeatureResult>() {
      @java.lang.Override
      public FeatureResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FeatureResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FeatureResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FeatureResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int PUBLISH_DATE_FIELD_NUMBER = 2;
  private long publishDate_;
  /**
   * <code>int64 publish_date = 2;</code>
   * @return The publishDate.
   */
  @java.lang.Override
  public long getPublishDate() {
    return publishDate_;
  }

  public static final int RESULT_FIELD_NUMBER = 3;
  private java.util.List<no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult> result_;
  /**
   * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
   */
  @java.lang.Override
  public java.util.List<no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult> getResultList() {
    return result_;
  }
  /**
   * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResultOrBuilder> 
      getResultOrBuilderList() {
    return result_;
  }
  /**
   * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
   */
  @java.lang.Override
  public int getResultCount() {
    return result_.size();
  }
  /**
   * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
   */
  @java.lang.Override
  public no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult getResult(int index) {
    return result_.get(index);
  }
  /**
   * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
   */
  @java.lang.Override
  public no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResultOrBuilder getResultOrBuilder(
      int index) {
    return result_.get(index);
  }

  public static final int LABEL_FIELD_NUMBER = 4;
  private volatile java.lang.Object label_;
  /**
   * <code>string label = 4;</code>
   * @return The label.
   */
  @java.lang.Override
  public java.lang.String getLabel() {
    java.lang.Object ref = label_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      label_ = s;
      return s;
    }
  }
  /**
   * <code>string label = 4;</code>
   * @return The bytes for label.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLabelBytes() {
    java.lang.Object ref = label_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      label_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (publishDate_ != 0L) {
      output.writeInt64(2, publishDate_);
    }
    for (int i = 0; i < result_.size(); i++) {
      output.writeMessage(3, result_.get(i));
    }
    if (!getLabelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, label_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (publishDate_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, publishDate_);
    }
    for (int i = 0; i < result_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, result_.get(i));
    }
    if (!getLabelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, label_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures)) {
      return super.equals(obj);
    }
    no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures other = (no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures) obj;

    if (getId()
        != other.getId()) return false;
    if (getPublishDate()
        != other.getPublishDate()) return false;
    if (!getResultList()
        .equals(other.getResultList())) return false;
    if (!getLabel()
        .equals(other.getLabel())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + PUBLISH_DATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPublishDate());
    if (getResultCount() > 0) {
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResultList().hashCode();
    }
    hash = (37 * hash) + LABEL_FIELD_NUMBER;
    hash = (53 * hash) + getLabel().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code java_feature_gen.NewsEntrySemanticFeatures}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:java_feature_gen.NewsEntrySemanticFeatures)
      no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeaturesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return no.tryxelindustries.java_feature_gen.entitys.protos.DatasetSemanticFeaturesProtos.internal_static_java_feature_gen_NewsEntrySemanticFeatures_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return no.tryxelindustries.java_feature_gen.entitys.protos.DatasetSemanticFeaturesProtos.internal_static_java_feature_gen_NewsEntrySemanticFeatures_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.class, no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.Builder.class);
    }

    // Construct using no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getResultFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      publishDate_ = 0L;

      if (resultBuilder_ == null) {
        result_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        resultBuilder_.clear();
      }
      label_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return no.tryxelindustries.java_feature_gen.entitys.protos.DatasetSemanticFeaturesProtos.internal_static_java_feature_gen_NewsEntrySemanticFeatures_descriptor;
    }

    @java.lang.Override
    public no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures getDefaultInstanceForType() {
      return no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.getDefaultInstance();
    }

    @java.lang.Override
    public no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures build() {
      no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures buildPartial() {
      no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures result = new no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.publishDate_ = publishDate_;
      if (resultBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          result_ = java.util.Collections.unmodifiableList(result_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.result_ = result_;
      } else {
        result.result_ = resultBuilder_.build();
      }
      result.label_ = label_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures) {
        return mergeFrom((no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures other) {
      if (other == no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getPublishDate() != 0L) {
        setPublishDate(other.getPublishDate());
      }
      if (resultBuilder_ == null) {
        if (!other.result_.isEmpty()) {
          if (result_.isEmpty()) {
            result_ = other.result_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureResultIsMutable();
            result_.addAll(other.result_);
          }
          onChanged();
        }
      } else {
        if (!other.result_.isEmpty()) {
          if (resultBuilder_.isEmpty()) {
            resultBuilder_.dispose();
            resultBuilder_ = null;
            result_ = other.result_;
            bitField0_ = (bitField0_ & ~0x00000001);
            resultBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getResultFieldBuilder() : null;
          } else {
            resultBuilder_.addAllMessages(other.result_);
          }
        }
      }
      if (!other.getLabel().isEmpty()) {
        label_ = other.label_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private long publishDate_ ;
    /**
     * <code>int64 publish_date = 2;</code>
     * @return The publishDate.
     */
    @java.lang.Override
    public long getPublishDate() {
      return publishDate_;
    }
    /**
     * <code>int64 publish_date = 2;</code>
     * @param value The publishDate to set.
     * @return This builder for chaining.
     */
    public Builder setPublishDate(long value) {
      
      publishDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 publish_date = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPublishDate() {
      
      publishDate_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult> result_ =
      java.util.Collections.emptyList();
    private void ensureResultIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        result_ = new java.util.ArrayList<no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult>(result_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult, no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult.Builder, no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResultOrBuilder> resultBuilder_;

    /**
     * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
     */
    public java.util.List<no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult> getResultList() {
      if (resultBuilder_ == null) {
        return java.util.Collections.unmodifiableList(result_);
      } else {
        return resultBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
     */
    public int getResultCount() {
      if (resultBuilder_ == null) {
        return result_.size();
      } else {
        return resultBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
     */
    public no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult getResult(int index) {
      if (resultBuilder_ == null) {
        return result_.get(index);
      } else {
        return resultBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
     */
    public Builder setResult(
        int index, no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultIsMutable();
        result_.set(index, value);
        onChanged();
      } else {
        resultBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
     */
    public Builder setResult(
        int index, no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult.Builder builderForValue) {
      if (resultBuilder_ == null) {
        ensureResultIsMutable();
        result_.set(index, builderForValue.build());
        onChanged();
      } else {
        resultBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
     */
    public Builder addResult(no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultIsMutable();
        result_.add(value);
        onChanged();
      } else {
        resultBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
     */
    public Builder addResult(
        int index, no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultIsMutable();
        result_.add(index, value);
        onChanged();
      } else {
        resultBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
     */
    public Builder addResult(
        no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult.Builder builderForValue) {
      if (resultBuilder_ == null) {
        ensureResultIsMutable();
        result_.add(builderForValue.build());
        onChanged();
      } else {
        resultBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
     */
    public Builder addResult(
        int index, no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult.Builder builderForValue) {
      if (resultBuilder_ == null) {
        ensureResultIsMutable();
        result_.add(index, builderForValue.build());
        onChanged();
      } else {
        resultBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
     */
    public Builder addAllResult(
        java.lang.Iterable<? extends no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult> values) {
      if (resultBuilder_ == null) {
        ensureResultIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, result_);
        onChanged();
      } else {
        resultBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
     */
    public Builder clearResult() {
      if (resultBuilder_ == null) {
        result_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        resultBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
     */
    public Builder removeResult(int index) {
      if (resultBuilder_ == null) {
        ensureResultIsMutable();
        result_.remove(index);
        onChanged();
      } else {
        resultBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
     */
    public no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult.Builder getResultBuilder(
        int index) {
      return getResultFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
     */
    public no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResultOrBuilder getResultOrBuilder(
        int index) {
      if (resultBuilder_ == null) {
        return result_.get(index);  } else {
        return resultBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
     */
    public java.util.List<? extends no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResultOrBuilder> 
         getResultOrBuilderList() {
      if (resultBuilder_ != null) {
        return resultBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(result_);
      }
    }
    /**
     * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
     */
    public no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult.Builder addResultBuilder() {
      return getResultFieldBuilder().addBuilder(
          no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult.getDefaultInstance());
    }
    /**
     * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
     */
    public no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult.Builder addResultBuilder(
        int index) {
      return getResultFieldBuilder().addBuilder(
          index, no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult.getDefaultInstance());
    }
    /**
     * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
     */
    public java.util.List<no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult.Builder> 
         getResultBuilderList() {
      return getResultFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult, no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult.Builder, no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResultOrBuilder> 
        getResultFieldBuilder() {
      if (resultBuilder_ == null) {
        resultBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult, no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult.Builder, no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResultOrBuilder>(
                result_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      return resultBuilder_;
    }

    private java.lang.Object label_ = "";
    /**
     * <code>string label = 4;</code>
     * @return The label.
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string label = 4;</code>
     * @return The bytes for label.
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string label = 4;</code>
     * @param value The label to set.
     * @return This builder for chaining.
     */
    public Builder setLabel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      label_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string label = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLabel() {
      
      label_ = getDefaultInstance().getLabel();
      onChanged();
      return this;
    }
    /**
     * <code>string label = 4;</code>
     * @param value The bytes for label to set.
     * @return This builder for chaining.
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      label_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:java_feature_gen.NewsEntrySemanticFeatures)
  }

  // @@protoc_insertion_point(class_scope:java_feature_gen.NewsEntrySemanticFeatures)
  private static final no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures();
  }

  public static no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NewsEntrySemanticFeatures>
      PARSER = new com.google.protobuf.AbstractParser<NewsEntrySemanticFeatures>() {
    @java.lang.Override
    public NewsEntrySemanticFeatures parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NewsEntrySemanticFeatures(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NewsEntrySemanticFeatures> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NewsEntrySemanticFeatures> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

