// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/news_dataset_semantic_features.proto

package no.tryxelindustries.java_feature_gen.entitys.protos;

public interface NewsEntrySemanticFeaturesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:java_feature_gen.NewsEntrySemanticFeatures)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int64 publish_date = 2;</code>
   * @return The publishDate.
   */
  long getPublishDate();

  /**
   * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
   */
  java.util.List<no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult> 
      getResultList();
  /**
   * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
   */
  no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResult getResult(int index);
  /**
   * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
   */
  int getResultCount();
  /**
   * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
   */
  java.util.List<? extends no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResultOrBuilder> 
      getResultOrBuilderList();
  /**
   * <code>repeated .java_feature_gen.NewsEntrySemanticFeatures.FeatureResult result = 3;</code>
   */
  no.tryxelindustries.java_feature_gen.entitys.protos.NewsEntrySemanticFeatures.FeatureResultOrBuilder getResultOrBuilder(
      int index);

  /**
   * <code>string label = 4;</code>
   * @return The label.
   */
  java.lang.String getLabel();
  /**
   * <code>string label = 4;</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();
}
